## Perceptron Algorithm

### Perceptrons as Logical Operators

**1. AND Operation**

In [ ]:
# AND operation
weight1 = 1.0
weight2 = 1.0
bias = -1.2


# Inputs and outputs
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [False, False, False, True]
outputs = []

# Generate and check output
for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = int(linear_combination >= 0)
    is_correct_string = 'Yes' if output == correct_output else 'No'
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])

# Print output
num_wrong = len([output[4] for output in outputs if output[4] == 'No'])
output_frame = pd.DataFrame(outputs, columns=['Input 1', '  Input 2', '  Linear Combination', '  Activation Output', '  Is Correct'])
if not num_wrong:
    print('Nice!  You got it all correct.\n')
else:
    print('You got {} wrong.  Keep trying!\n'.format(num_wrong))
print(output_frame.to_string(index=False))


**2. OR Operation**

From AND Operation to OR Operation

<img src=From_AND2OR.png>

**CASE ONE: Keep the weights still and increase the bias**

In [ ]:
# OR operation 1
## keep the weights still, and increase the bias!!
weight1 = 1.0  # keep still as in AND operation
weight2 = 1.0  # keep still as in AND operation
bias = -.8  # INCREASE the bias compared in AND oepration whose bias = -1.2


# Inputs and outputs
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [False, True, True, True]
outputs = []

# Generate and check output
for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = int(linear_combination >= 0)
    is_correct_string = 'Yes' if output == correct_output else 'No'
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])

# Print output
num_wrong = len([output[4] for output in outputs if output[4] == 'No'])
output_frame = pd.DataFrame(outputs, columns=['Input 1', '  Input 2', '  Linear Combination', '  Activation Output', '  Is Correct'])
if not num_wrong:
    print('Nice!  You got it all correct.\n')
else:
    print('You got {} wrong.  Keep trying!\n'.format(num_wrong))
print(output_frame.to_string(index=False))


**CASE TWO: Keep the bias still and increase the weights**

In [1]:
# OR operation
## keep the bias still, and increase the weights!!
weight1 = 1.2  # INCREASE the weights as in AND operation
weight2 = 1.2  # INCREASE the weights as in AND operation
bias = -1.2  # keep still as in AND operation


# Inputs and outputs
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [False, True, True, True]
outputs = []

# Generate and check output
for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = int(linear_combination >= 0)
    is_correct_string = 'Yes' if output == correct_output else 'No'
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])

# Print output
num_wrong = len([output[4] for output in outputs if output[4] == 'No'])
output_frame = pd.DataFrame(outputs, columns=['Input 1', '  Input 2', '  Linear Combination', '  Activation Output', '  Is Correct'])
if not num_wrong:
    print('Nice!  You got it all correct.\n')
else:
    print('You got {} wrong.  Keep trying!\n'.format(num_wrong))
print(output_frame.to_string(index=False))


Nice!  You got it all correct.

 Input 1    Input 2    Linear Combination    Activation Output   Is Correct
       0          0                  -1.2                    0          Yes
       0          1                   0.0                    1          Yes
       1          0                   0.0                    1          Yes
       1          1                   1.2                    1          Yes


**3. NOT Operation**

Unlike the other perceptrons above, the `NOT` operation only cares about one input. The operation returns a `0` if the input is `1` and a `1` if it's a `0`. The other inputs to the perceptron are ignored.

In [2]:
import pandas as pd

# TODO: Set weight1, weight2, and bias
weight1 = -0.5
weight2 = -1.1
bias = 1


# Inputs and outputs
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [True, False, True, False]
outputs = []

# Generate and check output
for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = int(linear_combination >= 0)
    is_correct_string = 'Yes' if output == correct_output else 'No'
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])

# Print output
num_wrong = len([output[4] for output in outputs if output[4] == 'No'])
output_frame = pd.DataFrame(outputs, columns=['Input 1', '  Input 2', '  Linear Combination', '  Activation Output', '  Is Correct'])
if not num_wrong:
    print('Nice!  You got it all correct.\n')
else:
    print('You got {} wrong.  Keep trying!\n'.format(num_wrong))
print(output_frame.to_string(index=False))

Nice!  You got it all correct.

 Input 1    Input 2    Linear Combination    Activation Output   Is Correct
       0          0                   1.0                    1          Yes
       0          1                  -0.1                    0          Yes
       1          0                   0.5                    1          Yes
       1          1                  -0.6                    0          Yes


In [3]:
def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])



In [7]:
np.matmul([1,2],[[3],[4]])+1

array([12])

In [8]:
np.matmul([1,2],[3,4])+1

12

In [9]:
w = np.array([3,4]).reshape(-1, 1)
w

array([[3],
       [4]])

In [11]:
prediction([1,1],[[1],[-1]],1)

1

In [12]:
prediction([-1,1],[[1],[-1]],1)

0

In [17]:
np.random.rand(1)

array([0.80719682])

In [14]:
X=np.array([1,2])
X.T

array([1, 2])

In [15]:
X = np.array([[1,2],[3,4],[5,6]])
X.T

array([[1, 3, 5],
       [2, 4, 6]])

In [16]:
max(X.T[0])

5

### Example: Coding the Perceptron Algorithm

<img src=data_viz_coding_percAlgo.png>

The perceptron step works as follows. For a point with coordinates `(p,q)`, label `y`, and prediction given by the equation $\hat{y} = step(w_1x_1 + w_2x_2 + b) $
- If the point is correctly classified, do nothing.
- If the point is misclassified _positive_, but it has a **negative** label, subtract $\alpha p$, $\alpha q$,and $\alpha {}$ from $w_1$, $w_2$,and $b$ respectively.
- If the point is misclassified _negative_, but it has a **positive** label, add $\alpha p$, $\alpha q$,and $\alpha {}$ from $w_1$, $w_2$,and $b$ respectively. 

Run to graph the solution that the perceptron algorithm gives you. It'll actually draw a set of dotted lines, that show how the algorithm approaches to the best solution, given by the black solid line.

These parameters may affect the solution:
- number of epochs
- learning rate
- initial weights and bias

Change them to see how they will affect!

In [18]:
import numpy as np
# Setting the random seed, it can be changed to see different solutions.
np.random.seed(40)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0


def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])


def perceptronStep(X, y, W, b, learn_rate = 0.01):
    """
    Update weights and bias whenever needed.
    
    Parameters:
    ----------
        X: a n_by_2 numpy 2D array. Each entry represents a set of coordinates. 
           It represents the 0th and 1st column in data.csv.
           
        y: actual labels for the datapoints. It represents the 2nd column in data.csv
        
        W: a 2_by_1 2D numpy array. Weights for the linear equation.
        
        b: Bias value for the linear equation.
        
        learning_rate: float. small steps in changing weights and bias when necessary.
     
     Returns:
        new weights and bias.    
    
    """
    for i in range(len(X)):
        y_hat = prediction(X[i],W,b)
        
        if y[i]-y_hat == 1:  # predicted neg but actually it's pos
            W[0] += X[i][0]*learn_rate
            W[1] += X[i][1]*learn_rate
            b += learn_rate
            
        elif y[i]-y_hat == -1:  # predicted pos but actually it's neg
            W[0] -= X[i][0]*learn_rate
            W[1] -= X[i][1]*learn_rate
            b -= learn_rate
            
    return W, b    


def trainPerceptronAlgorithm(X, y, learn_rate = 0.001, num_epochs = 50):
    """
    Runs the perceptron algorithm repeatedly on the dataset, and returns 
    a few of the boundary lines obtained in the iterations, for plotting purposes.
    """
    x_min, x_max = min(X.T[0]), max(X.T[0])  # the minimum and maximun value in Variable x0 (column 0 in data.csv)
    y_min, y_max = min(X.T[1]), max(X.T[1])  # the minimum and maximun value in Variable x1 (column 1 in data.csv)
    
    W = np.array(np.random.rand(2,1))  # Initialize the W weights between (0, 1)
    b = np.random.rand(1)[0] + x_max  # Initialize the Bias b between (0, 1)
    
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        
        # each entry in the boundary_lines represents a linear equation.
        boundary_lines.append((-W[0]/W[1], -b/W[1])) 
    print(boundary_lines)
    return boundary_lines

# define the graph function
def graph_lines():
    pass

### From Step function to Sigmoid function

sigmoid function:

$
\begin{align}
\sigma(x) =  \frac{1}{1+e^{-x}}
\end{align}
$

In [25]:
def sig(x):
    return 1/(1+np.exp(-x))

def linear_eq(W, X, b):
    return np.matmul(W, X) + b



def predict(W, X, b):
    res = []
    for entry in X:
        linRes = linear_eq(W, entry, b)
        sig_res = sig(linRes)
        res.append(sig_res)
    return res

In [26]:
W = np.array([4,5])
b = -9
X = np.array([[-4,5],[1,1]])


In [31]:
X = np.array([1,1,2,4,5,-5,-4,5]).reshape((4,2))
X

array([[ 1,  1],
       [ 2,  4],
       [ 5, -5],
       [-4,  5]])

In [30]:
predict(W, X, b)

[0.5, 0.9999999943972036, 8.315280276641321e-07, 0.5]

## Softmax Function

Linear function scores:  
$Z_1, Z_2, Z_3, \dots , Z_n$, where n means number of classes,

$
\begin{align}
P(class i) = \frac{e^Z_i}{e^{Z_1} + e^{Z_2} + e^{Z_3} + \dots + e^{Z_n}}
\end{align}
$

***NOTE:*** When $n=2$, softmax funciton collpases to **sigmoid function**.

In [33]:
def softmax(L):
    """
    mapping a list to softmax values.
    
    parameters:
    -----------
        L: list-like array.
        
    Returns:
    --------
        numpy.array
    """
    denominator = np.exp(L).sum()
    numerator = np.exp(L)
    return np.divide(numerator, denominator)

softmax([5,6,7])
    

array([0.09003057, 0.24472847, 0.66524096])

## Cross entropy

Formula for cross entropy: where `y` is for the category, and `p` is for the probability.

$
\begin{align}
Cross-Entropy = -\sum_{i=1}^m[y_{i}ln(p_i) + (1-y_i)ln(1-p_i)]
\end{align}
$

<img src=cross_entropy.png>

In [56]:
def cross_entropy(Y, P):
    Y = np.float_(Y)
    P = np.float_(P)
    return -np.sum(Y*np.log(P)+(1-Y)*np.log(1-P))

In [57]:
cross_entropy([0,0,1], [.8,.7,.1])

5.115995809754082

### Multi-Class Cross Entropy

**Formula:**

$
\begin{align}
ce = -\sum_{i=1}^{n}\sum_{j=1}^{m}y_{ij}ln(p_{ij})
\end{align}
$
, where `j` represents the class.